package com.claim.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class food_wine {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int AutoGeneratedID;
	
	@Column
	private String WineID;
	
	@Column 
	private String WineName;
	
	@Column 
	private int WinePrice;
	@Column 
	private String WineDescrip;
	@Column 
	private String Vintage;
	@Column 
	private String Label_IMG_ID;
	@Column 
	private boolean WineAvailable;
	@Column 
	private String FoodMenuID;
	@Column 
	private int FoodPrice;
	@Column 
	private String FoodName;
	@Column 
	private String FoodDescrip;
	@Column 
	private String Food_IMG_ID;
	@Column 
	private boolean FoodAvailable;
	@Column 
	private boolean ApplyMemberDiscount;
	@Column 
	private boolean ApplySmallPairingRate;
	@Column
	private String type;
	@Column
	private String wineLabel;
	
	
	
	
	
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getWineLabel() {
		return wineLabel;
	}
	public void setWineLabel(String wineLabel) {
		this.wineLabel = wineLabel;
	}
	public int getAutoGeneratedID() {
		return AutoGeneratedID;
	}
	public void setAutoGeneratedID(int autoGeneratedID) {
		AutoGeneratedID = autoGeneratedID;
	}
	public String getWineID() {
		return WineID;
	}
	public void setWineID(String wineID) {
		WineID = wineID;
	}
	public String getWineName() {
		return WineName;
	}
	public void setWineName(String wineName) {
		WineName = wineName;
	}
	public int getWinePrice() {
		return WinePrice;
	}
	public void setWinePrice(int winePrice) {
		WinePrice = winePrice;
	}
	public String getWineDescrip() {
		return WineDescrip;
	}
	public void setWineDescrip(String wineDescrip) {
		WineDescrip = wineDescrip;
	}
	public String getVintage() {
		return Vintage;
	}
	public void setVintage(String vintage) {
		Vintage = vintage;
	}
	public String getLabel_IMG_ID() {
		return Label_IMG_ID;
	}
	public void setLabel_IMG_ID(String label_IMG_ID) {
		Label_IMG_ID = label_IMG_ID;
	}
	public boolean isWineAvailable() {
		return WineAvailable;
	}
	public void setWineAvailable(boolean wineAvailable) {
		WineAvailable = wineAvailable;
	}
	public String getFoodMenuID() {
		return FoodMenuID;
	}
	public void setFoodMenuID(String foodMenuID) {
		FoodMenuID = foodMenuID;
	}
	public int getFoodPrice() {
		return FoodPrice;
	}
	public void setFoodPrice(int foodPrice) {
		FoodPrice = foodPrice;
	}
	public String getFoodName() {
		return FoodName;
	}
	public void setFoodName(String foodName) {
		FoodName = foodName;
	}
	public String getFoodDescrip() {
		return FoodDescrip;
	}
	public void setFoodDescrip(String foodDescrip) {
		FoodDescrip = foodDescrip;
	}
	public String getFood_IMG_ID() {
		return Food_IMG_ID;
	}
	public void setFood_IMG_ID(String food_IMG_ID) {
		Food_IMG_ID = food_IMG_ID;
	}
	public boolean isFoodAvailable() {
		return FoodAvailable;
	}
	public void setFoodAvailable(boolean foodAvailable) {
		FoodAvailable = foodAvailable;
	}
	public boolean isApplyMemberDiscount() {
		return ApplyMemberDiscount;
	}
	public void setApplyMemberDiscount(boolean applyMemberDiscount) {
		ApplyMemberDiscount = applyMemberDiscount;
	}
	public boolean isApplySmallPairingRate() {
		return ApplySmallPairingRate;
	}
	public void setApplySmallPairingRate(boolean applySmallPairingRate) {
		ApplySmallPairingRate = applySmallPairingRate;
	}
	@Override
	public String toString() {
		return "food_wine [AutoGeneratedID=" + AutoGeneratedID + ", WineID=" + WineID + ", WineName=" + WineName
				+ ", WinePrice=" + WinePrice + ", WineDescrip=" + WineDescrip + ", Vintage=" + Vintage
				+ ", Label_IMG_ID=" + Label_IMG_ID + ", WineAvailable=" + WineAvailable + ", FoodMenuID=" + FoodMenuID
				+ ", FoodPrice=" + FoodPrice + ", FoodName=" + FoodName + ", FoodDescrip=" + FoodDescrip
				+ ", Food_IMG_ID=" + Food_IMG_ID + ", FoodAvailable=" + FoodAvailable + ", ApplyMemberDiscount="
				+ ApplyMemberDiscount + ", ApplySmallPairingRate=" + ApplySmallPairingRate + ", type=" + type
				+ ", wineLabel=" + wineLabel + "]";
	}
	

}
